-- =====================================================================
--  CASH DENOMINATION CATALOG — Steps 1, 2, 3
--  Copy-paste into the Supabase SQL editor and Run as ONE script.
--
--  Equivalent to migrations d1a01 / d2a02.
--  Wrapped in a single transaction: if any statement fails, NOTHING is
--  applied. Re-runnable — every step guards against double-application.
--
--  Goal: adding a cash denomination becomes a single INSERT into
--  pettycashv2.cash_info — no schema change, no code change. Today a
--  denomination needs a migration, a model column, a template edit, and a
--  new hardcoded multiplier in FOUR separate places.
--
--  This does NOT drop any columns. The nine note/coin columns on
--  report_cashcount_draft stay exactly as they are; dropping them is a
--  separate script to be run only after the checks at the bottom return
--  zero rows. They have five independent readers (see Step 4 in the
--  runbook) — considerably more entangled than the sales columns were.
--
--  If you run migrations with Alembic instead, use the .py files and do NOT
--  run this — you would apply the same changes twice (harmless, but the
--  alembic_version table would not know about them).
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- STEP 1 — reshape cash_info into a real catalog + seed HKD
--
-- cash_info has existed since 0001_full_schema but was never seeded and is
-- read by nothing: the face values live as literals in cash_count.py:300-309
-- and AGAIN in ending.py:666, 1157 and 1279.
-- ---------------------------------------------------------------------

-- The FK to country_info must come off before the type change and go back
-- after — Postgres will not alter a column another constraint depends on.
DO $$
DECLARE fk_name text;
BEGIN
    SELECT c.conname INTO fk_name
    FROM pg_constraint c
    WHERE c.contype = 'f'
      AND c.conrelid = 'pettycashv2.cash_info'::regclass
      AND c.confrelid = 'pettycashv2.country_info'::regclass;
    IF fk_name IS NOT NULL THEN
        EXECUTE format(
            'ALTER TABLE pettycashv2.cash_info DROP CONSTRAINT %I', fk_name);
    END IF;
END $$;

-- varchar(3) -> char(2). c8e0a2b4d6f8 rebuilt country_info with a char(2) PK
-- and restored this FK verbatim (varchar -> char(2) is a valid reference, so
-- nothing broke), but the column still cannot hold a clean 'HK' comparison.
-- TRIM guards a deployment that seeded it by hand with an alpha-3 code.
DO $$
BEGIN
    IF (SELECT data_type FROM information_schema.columns
        WHERE table_schema = 'pettycashv2' AND table_name = 'cash_info'
          AND column_name = 'country_code') <> 'character' THEN
        ALTER TABLE pettycashv2.cash_info
            ALTER COLUMN country_code TYPE char(2)
            USING LEFT(TRIM(country_code), 2);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_cash_info_country_code'
    ) THEN
        ALTER TABLE pettycashv2.cash_info
            ADD CONSTRAINT fk_cash_info_country_code
            FOREIGN KEY (country_code)
            REFERENCES pettycashv2.country_info(country_code);
    END IF;
END $$;

-- cash_id was a bare integer PK with no default, so every INSERT had to
-- supply its own id. Adding a denomination from the app would have needed a
-- MAX(cash_id)+1 race.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_attribute
        WHERE attrelid = 'pettycashv2.cash_info'::regclass
          AND attname = 'cash_id' AND attidentity <> ''
    ) THEN
        ALTER TABLE pettycashv2.cash_info
            ALTER COLUMN cash_id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

ALTER TABLE pettycashv2.cash_info
    ADD COLUMN IF NOT EXISTS display_order integer NOT NULL DEFAULT 999,
    -- Retires a denomination without deleting the historical counts that
    -- reference it.
    ADD COLUMN IF NOT EXISTS is_active     boolean NOT NULL DEFAULT true;

-- A country cannot have two rows for the same face value of the same kind.
-- This is also what the seed upserts on.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_cash_info_country_value_type'
    ) THEN
        ALTER TABLE pettycashv2.cash_info
            ADD CONSTRAINT uq_cash_info_country_value_type
            UNIQUE (country_code, cash_value, type);
    END IF;
END $$;

-- The cash count form's read path: denominations for one country, in order.
CREATE INDEX IF NOT EXISTS ix_cash_info_country_order
    ON pettycashv2.cash_info (country_code, display_order);

-- Seed HKD. Face values sourced from the hardcoded multipliers in
-- cash_count.py:300-309. Notes descend then coins descend; display_order is
-- global across both so the form renders one continuous list.
--
-- These nine rows are EXACTLY the denominations the cash count form can post
-- today (the nine actual_cash[...] fields in cash_count.html:237-245). The
-- catalog and the form agree, so nothing is offered that cannot be recorded.
--
-- Deliberately NOT seeded, pending the form rendering from this catalog:
--
--   * HK$200 note. cash_count.py parses actual_cash[note200] and adds it to
--     the running total, but there is no form field and no column, so the
--     value is dropped on save. Seeding it would put a denomination in the
--     catalog that cannot be recorded.
--   * HK$10 coin. Circulates alongside the HK$10 note. The template has a
--     '10coins' input with an id but no name, so it never posts either.
--
-- Both are one INSERT away once the form loops over this table — that is the
-- whole point of the catalog. Add them at the same time, not before.
--
-- Fails loudly if country_info has no HK row rather than tripping an opaque
-- FK violation.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pettycashv2.country_info WHERE country_code = 'HK'
    ) THEN
        RAISE EXCEPTION
            'country_info has no HK row — run the a2c4e6b8d0f2 country seed first';
    END IF;
END $$;

INSERT INTO pettycashv2.cash_info
    (country_code, type, cash_value, cash_name, "desc", display_order, is_active)
VALUES
    ('HK', 'note', 1000, '$1,000', 'HK$1,000 note',  1, true),
    ('HK', 'note',  500, '$500',   'HK$500 note',    2, true),
    ('HK', 'note',  100, '$100',   'HK$100 note',    3, true),
    ('HK', 'note',   50, '$50',    'HK$50 note',     4, true),
    ('HK', 'note',   20, '$20',    'HK$20 note',     5, true),
    ('HK', 'note',   10, '$10',    'HK$10 note',     6, true),
    ('HK', 'coin',    5, '$5',     'HK$5 coin',      7, true),
    ('HK', 'coin',    2, '$2',     'HK$2 coin',      8, true),
    ('HK', 'coin',    1, '$1',     'HK$1 coin',      9, true)
ON CONFLICT (country_code, cash_value, type) DO UPDATE SET
    cash_name     = EXCLUDED.cash_name,
    "desc"        = EXCLUDED."desc",
    display_order = EXCLUDED.display_order;


-- ---------------------------------------------------------------------
-- STEP 2 — per-denomination count storage + per-entity choice
--
-- report_cashcount_detail is the cash-count equivalent of
-- report_sale_detail: one row per (report, denomination).
--
-- It hangs off report_draft, matching where report_cashcount_draft already
-- points. A report and its draft share one id (ending.py:445), so one set of
-- rows serves both — the same reason the sales runbook warns against adding a
-- separate report_draft_id to report_sale_detail.
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS pettycashv2.report_cashcount_detail (
    id          varchar(36) PRIMARY KEY,
    report_id   varchar(36) NOT NULL
                REFERENCES pettycashv2.report_draft(id) ON DELETE CASCADE,
    -- RESTRICT, not CASCADE: deleting a denomination must never silently
    -- delete the historical counts referencing it. Retire with is_active.
    cash_id     integer     NOT NULL
                REFERENCES pettycashv2.cash_info(cash_id) ON DELETE RESTRICT,
    -- Quantity counted. Integer — you cannot hold half a note.
    count       integer     NOT NULL DEFAULT 0,
    -- Face value AS AT the time of counting. Denormalised on purpose: if a
    -- denomination is ever revalued or retired, historical reports must still
    -- total to what was actually counted that day.
    cash_value  double precision NOT NULL,
    created_at  timestamp   DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamp   DEFAULT CURRENT_TIMESTAMP,
    -- One count per denomination per report. This is what the app's upsert
    -- targets, and what stops a double-submit doubling a total.
    CONSTRAINT uq_cashcount_detail_report_cash UNIQUE (report_id, cash_id)
);

CREATE INDEX IF NOT EXISTS ix_cashcount_detail_report
    ON pettycashv2.report_cashcount_detail (report_id);

-- Which denominations an entity actually logs. A row exists ONLY where the
-- entity diverges from its country default, so an entity with no rows sees
-- every active cash_info row for its country and automatically picks up
-- denominations added later. That is why there is no per-entity seed here.
--
-- Deliberately NOT reusing entity_cash_detail_v2 (entity_id + cash_id,
-- already exists, already FKs both sides): it holds cash_instock, a running
-- quantity-on-hand. Overloading it would make a row's absence ambiguous
-- between "not stocked" and "not tracked", and enabling a denomination would
-- silently invent a stock figure. It stays untouched.
CREATE TABLE IF NOT EXISTS pettycashv2.entity_cash_denomination (
    id            varchar(36) PRIMARY KEY,
    entity_id     varchar(36) NOT NULL
                  REFERENCES pettycashv2.entities(id) ON DELETE CASCADE,
    cash_id       integer     NOT NULL
                  REFERENCES pettycashv2.cash_info(cash_id) ON DELETE CASCADE,
    -- FALSE hides a country default this entity never handles (a shop that
    -- refuses HK$1,000 notes).
    enabled       boolean     NOT NULL DEFAULT true,
    -- NULL inherits cash_info.display_order. Set only when an entity
    -- reorders its own list.
    display_order integer,
    created_at    timestamp   DEFAULT CURRENT_TIMESTAMP,
    updated_at    timestamp   DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_entity_cash_denomination UNIQUE (entity_id, cash_id)
);

CREATE INDEX IF NOT EXISTS ix_entity_cash_denomination_entity
    ON pettycashv2.entity_cash_denomination (entity_id);


-- ---------------------------------------------------------------------
-- STEP 3 — BACKFILL: nine columns -> detail rows   ** MOVES REAL DATA **
--
-- GUARD RULE — per REPORT, not per denomination:
--   only reports with NO detail rows at all are backfilled.
-- Same rationale as the sales backfill: a per-denomination guard would
-- insert missing ones alongside app-written rows and silently disagree with
-- what is displayed. Per-report is the only safe granularity.
--
-- Only HK denominations are targeted. Every historical count was entered
-- through a form whose face values were hardcoded HKD, so HK is what those
-- numbers mean regardless of the entity's country_code. Mapping them to
-- another country's catalog would silently revalue them.
--
-- Zero and NULL counts are skipped — the columns default to 0 and most
-- reports leave most denominations empty. A missing row reads as zero
-- (the service layer coalesces), so totals are identical either way.
--
-- There is no note200 column to backfill. Any HK$200 a user typed before
-- this was multiplied into the total and then dropped on save, so there is
-- nothing recoverable — the value was never persisted anywhere.
-- ---------------------------------------------------------------------

WITH src AS (
    SELECT cd.report_id, v.cash_value, v.kind, v.count
    FROM pettycashv2.report_cashcount_draft cd
    CROSS JOIN LATERAL (VALUES
        (1000::double precision, 'note', cd.thousand_note),
        ( 500::double precision, 'note', cd.fivehundred_note),
        ( 100::double precision, 'note', cd.onehundred_note),
        (  50::double precision, 'note', cd.fifty_note),
        (  20::double precision, 'note', cd.twenty_note),
        (  10::double precision, 'note', cd.ten_note),
        (   5::double precision, 'coin', cd.five_coin),
        (   2::double precision, 'coin', cd.two_coin),
        (   1::double precision, 'coin', cd.one_coin)
    ) AS v(cash_value, kind, count)
    WHERE v.count IS NOT NULL AND v.count <> 0
      -- A draft deleted between migrations simply has no row here; the FK holds.
      AND EXISTS (
          SELECT 1 FROM pettycashv2.report_draft d WHERE d.id = cd.report_id
      )
      AND NOT EXISTS (
          SELECT 1 FROM pettycashv2.report_cashcount_detail x
          WHERE x.report_id = cd.report_id
      )
)
INSERT INTO pettycashv2.report_cashcount_detail
    (id, report_id, cash_id, count, cash_value, created_at, updated_at)
SELECT
    gen_random_uuid()::text,
    src.report_id, ci.cash_id, src.count, ci.cash_value, NOW(), NOW()
FROM src
JOIN pettycashv2.cash_info ci
  ON ci.country_code = 'HK'
 AND ci.cash_value = src.cash_value
 AND ci.type = src.kind;

COMMIT;


-- =====================================================================
--  POST-RUN CHECKS — run these AFTER the script above commits.
-- =====================================================================

-- A. Catalog seeded? Expect 9 HK rows + however many custom rows.
SELECT country_code, count(*)
FROM pettycashv2.cash_info GROUP BY 1 ORDER BY 2 DESC;

-- B. Every seeded denomination has an id and is active? Expect 10 rows,
--    display_order 1..10, no NULL cash_id.
SELECT cash_id, type, cash_value, cash_name, display_order, is_active
FROM pettycashv2.cash_info WHERE country_code = 'HK'
ORDER BY display_order;

-- C. Entities whose country has no denominations. These would render an
--    EMPTY cash count form. Expect 0 rows — every entity should be HK until
--    another country is seeded.
SELECT e.id, e.name, e.country_code
FROM pettycashv2.entities e
WHERE e.status = 'active'
  AND NOT EXISTS (
      SELECT 1 FROM pettycashv2.cash_info ci
      WHERE ci.country_code = e.country_code AND ci.is_active
  );

-- D. *** THE GATE FOR DROPPING THE NINE COLUMNS ***
--     Column-derived total vs detail-row total, per report. Uses the same
--     arithmetic cash_count.py:300-323 uses today.
--     MUST RETURN ZERO ROWS before the columns are dropped.
--     The catalog holds exactly the nine denominations these columns cover,
--     so any row returned here is a genuine mismatch — investigate it.
SELECT
    cd.report_id,
    (COALESCE(cd.thousand_note,0)    * 1000
   + COALESCE(cd.fivehundred_note,0) *  500
   + COALESCE(cd.onehundred_note,0)  *  100
   + COALESCE(cd.fifty_note,0)       *   50
   + COALESCE(cd.twenty_note,0)      *   20
   + COALESCE(cd.ten_note,0)         *   10
   + COALESCE(cd.five_coin,0)        *    5
   + COALESCE(cd.two_coin,0)         *    2
   + COALESCE(cd.one_coin,0)         *    1) AS column_total,
    COALESCE((
        SELECT SUM(d.count * d.cash_value)
        FROM pettycashv2.report_cashcount_detail d
        WHERE d.report_id = cd.report_id
    ), 0) AS detail_total
FROM pettycashv2.report_cashcount_draft cd
WHERE EXISTS (
    SELECT 1 FROM pettycashv2.report_cashcount_detail d
    WHERE d.report_id = cd.report_id
)
AND ABS(
    (COALESCE(cd.thousand_note,0)    * 1000
   + COALESCE(cd.fivehundred_note,0) *  500
   + COALESCE(cd.onehundred_note,0)  *  100
   + COALESCE(cd.fifty_note,0)       *   50
   + COALESCE(cd.twenty_note,0)      *   20
   + COALESCE(cd.ten_note,0)         *   10
   + COALESCE(cd.five_coin,0)        *    5
   + COALESCE(cd.two_coin,0)         *    2
   + COALESCE(cd.one_coin,0)         *    1)
    - COALESCE((
        SELECT SUM(d.count * d.cash_value)
        FROM pettycashv2.report_cashcount_detail d
        WHERE d.report_id = cd.report_id
    ), 0)
) > 0.01;

-- E. Stored actual_cash_total vs detail rows. actual_cash_total feeds the
--    NEXT DAY'S opening balance (opening.py:1044, create.py:284), so a
--    mismatch here propagates forward. Expect 0 rows.
SELECT cd.report_id, cd.actual_cash_total,
       SUM(d.count * d.cash_value) AS detail_total
FROM pettycashv2.report_cashcount_draft cd
JOIN pettycashv2.report_cashcount_detail d ON d.report_id = cd.report_id
GROUP BY cd.report_id, cd.actual_cash_total
HAVING ABS(COALESCE(cd.actual_cash_total,0) - SUM(d.count * d.cash_value)) > 0.01;


-- =====================================================================
--  ROLLBACK — only removes what this script created.
--  The nine columns were never cleared, so dropping the backfilled rows
--  loses nothing.
-- =====================================================================
-- BEGIN;
-- DELETE FROM pettycashv2.report_cashcount_detail
--  WHERE cash_id IN (SELECT cash_id FROM pettycashv2.cash_info
--                     WHERE country_code = 'HK');
-- DROP TABLE IF EXISTS pettycashv2.entity_cash_denomination;
-- DROP TABLE IF EXISTS pettycashv2.report_cashcount_detail;
-- DELETE FROM pettycashv2.cash_info WHERE country_code = 'HK';
-- COMMIT;
