"""create consent & terms tables

Autogenerated from the SQLAlchemy models in ``blueprints/consent/models/``
(terms_version, terms_user_principal, consent_record, consent_event), then
trimmed to just those four tables -- the local autogenerate run reported every
table as "added" because the dev DB is empty, so the unrelated create/drop ops
were removed by hand.

The ``user`` table already exists (``pettycashv2.user``) and is only
referenced via FK. Every column is NOT NULL except ``terms_version.superseded_at``.

Revision ID: 093b4bd031f1
Revises: a9c1e3f5b7d2
Create Date: 2026-06-19 16:32:08.987972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '093b4bd031f1'
down_revision = 'a9c1e3f5b7d2'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('terms_version',
    sa.Column('terms_ver_id', sa.String(length=36), nullable=False),
    sa.Column('doc_url', sa.Text(), nullable=False),
    sa.Column('ver_label', sa.Text(), nullable=False),
    sa.Column('jurisdiction', sa.Text(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('superseded_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('terms_ver_id'),
    schema='pettycashv2'
    )
    op.create_table('terms_user_principal',
    sa.Column('principal_id', sa.String(length=36), nullable=False),
    sa.Column('account_ref', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['account_ref'], ['pettycashv2.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('principal_id'),
    sa.UniqueConstraint('account_ref'),
    schema='pettycashv2'
    )
    op.create_table('consent_record',
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=36), nullable=False),
    sa.Column('terms_ver_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('captured_ip', postgresql.INET(), nullable=False),
    sa.Column('captured_ua', sa.Text(), nullable=False),
    sa.Column('capture_method', sa.Text(), nullable=False),
    sa.Column('record_hash', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['pettycashv2.terms_user_principal.principal_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['terms_ver_id'], ['pettycashv2.terms_version.terms_ver_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('record_id'),
    schema='pettycashv2'
    )
    with op.batch_alter_table('consent_record', schema='pettycashv2') as batch_op:
        batch_op.create_index(batch_op.f('ix_pettycashv2_consent_record_principal_id'), ['principal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pettycashv2_consent_record_terms_ver_id'), ['terms_ver_id'], unique=False)

    op.create_table('consent_event',
    sa.Column('event_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('event_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('event_state', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('recorded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['pettycashv2.consent_record.record_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id'),
    schema='pettycashv2'
    )
    with op.batch_alter_table('consent_event', schema='pettycashv2') as batch_op:
        batch_op.create_index(batch_op.f('ix_pettycashv2_consent_event_record_id'), ['record_id'], unique=False)


def downgrade():
    with op.batch_alter_table('consent_event', schema='pettycashv2') as batch_op:
        batch_op.drop_index(batch_op.f('ix_pettycashv2_consent_event_record_id'))

    op.drop_table('consent_event', schema='pettycashv2')
    with op.batch_alter_table('consent_record', schema='pettycashv2') as batch_op:
        batch_op.drop_index(batch_op.f('ix_pettycashv2_consent_record_terms_ver_id'))
        batch_op.drop_index(batch_op.f('ix_pettycashv2_consent_record_principal_id'))

    op.drop_table('consent_record', schema='pettycashv2')
    op.drop_table('terms_user_principal', schema='pettycashv2')
    op.drop_table('terms_version', schema='pettycashv2')
