# -*- coding: utf-8 -*-
"""Render APPLICATION_CHANGES.md from the model audit."""
import io, os, subprocess, sys, collections, re

SP = os.path.dirname(os.path.abspath(__file__))
OUT = r"c:\dev\Minty\docs\schema\APPLICATION_CHANGES.md"

env = dict(os.environ); env["PYTHONUTF8"] = "1"
raw = subprocess.run([sys.executable, os.path.join(SP, "audit_models.py")],
                     capture_output=True, text=True, env=env, encoding="utf-8").stdout

rows = []
for line in raw.splitlines():
    m = re.match(r"^(Minty|billing-backend)\s+(TABLE|MISSING|TYPE)\s+(\S+)\s+(\S+):(\d+)\s+(.*)$", line)
    if m:
        rows.append(dict(repo=m.group(1), kind=m.group(2), table=m.group(3),
                         file=m.group(4), line=int(m.group(5)), what=m.group(6).strip()))

tables  = [r for r in rows if r["kind"] == "TABLE"]
missing = [r for r in rows if r["kind"] == "MISSING"]
types   = [r for r in rows if r["kind"] == "TYPE"]

RENAME = {
    "invitations": "invitation", "roles": "role", "permissions": "permission",
    "role_permissions": "role_permission", "report_sale_detail": "report_sale",
    "shop_expense": "report_expense", "entity_cash_detail_v2": "entity_cash_detail",
    "audit": "bill_audit", "bill_line_item": "bill_line",
}

def link(r):
    return "[%s:%d](%s#L%d)" % (r["file"], r["line"], r["file"], r["line"])

d = []
w = d.append
w("# Application changes required by `pettycash_test`")
w("")
w("Generated, not hand-written. Regenerate after any schema or model change:")
w("")
w("```")
w("python docs/schema/generators/audit_models.py     # the raw findings")
w("python docs/schema/generators/mkdoc.py            # this document")
w(".venv/Scripts/python.exe docs/schema/generators/mkdocx.py   # the .docx beside it")
w("```")
w("")
w("It compares every model in **Minty** (SQLAlchemy) and **billing-backend** (Django)")
w("against the schema `01_schema_rebased.sql` builds, and reports three things: a")
w("model whose table no longer exists under that name, a model column the schema")
w("does not have, and a declared type that no longer matches the column.")
w("")
w("Paths are relative to each repo root — `c:\\dev\\Minty` and `c:\\dev\\billing-backend`.")
w("")
w("**%d findings: %d table, %d column, %d type.**" % (len(rows), len(tables), len(missing), len(types)))
w("")
w("> The audit reads source with `utf-8-sig`. Several of these files carry a BOM,")
w("> and an earlier version used `utf-8`, so `ast.parse` raised and the file was")
w("> skipped silently — which hid the entire `User` model and 57 other findings.")
w("> The script now reports any file it cannot parse instead of skipping quietly.")
w("")
w("---")
w("")
w("## 0. Six open decisions — the code side")
w("")
w("The schema files carry these as **D1–D6** (`DECISIONS REQUIRED AT REVIEW` in")
w("`01_schema_rebased.sql`, and again beside the statement each one lands on in `02`/`03`).")
w("This is what each costs *here*, in the application.")
w("")
w("The enums were widened so the merge would be lossless. The consequence is that where the")
w("merged data and the code disagree, **the database accepts both and nothing raises** — the")
w("feature just returns nothing. None of these is a crash; all of them are silent.")
w("")
w("| | column | if the DATA wins (map on the way in) | if the CODE wins (change these) |")
w("|---|---|---|---|")
w("| **D3** | `report.status` — 3,724 rows say `published`, code says `posted` | one mapping in `03` | [ending.py:483](blueprints/report/services/ending.py#L483), [:1568](blueprints/report/services/ending.py#L1568), [history_query.py:90](blueprints/report/services/history_query.py#L90), [:111](blueprints/report/services/history_query.py#L111), [report.py:51](blueprints/report/models/report.py#L51) |")
w("| **D4** | `sale_info.type` — data `electric`/`delivery`, code `Electronic`/`Delivery` | one mapping in `03` | **46 Python sites** — [onboarding_state.py:166](blueprints/entity/services/onboarding_state.py#L166), [:172-173](blueprints/entity/services/onboarding_state.py#L172-L173), [payment_methods.py:89](blueprints/entity/services/payment_methods.py#L89), [:209](blueprints/entity/services/payment_methods.py#L209), [:268](blueprints/entity/services/payment_methods.py#L268), [sale_info.py:109](blueprints/entity/models/sale_info.py#L109) — **plus five** `electronic_delivery_*` templates |")
w("| **D5** | `invitation.status` — 40 rows say `revoked`, code writes `cancelled` | one mapping in `02` | one site |")
w("")
w("**D1** and **D2** have no code side. They are data already lost upstream, in the schema-2")
w("build, before `02`/`03` read it — 460 `report.discrepancy_type` rows flattened to `none`,")
w("and 9 entities folded into `onboarding`. Recovering them means fixing that build; leaving")
w("them means the code keeps writing values the migrated data never shows.")
w("")
w("D4 is the one to look at twice. `electric` is a misspelling of *electronic*, so letting the")
w("data win writes a typo permanently into 46 call sites and five templates.")
w("")
w("---")
w("")
w("## D6 — fix the schema, not the code")
w("")
w("One finding is the schema's fault and should not be worked around in the app.")
w("")
w("### `user.system_role` does not exist")
w("")
w("`01_schema_rebased.sql` declares the enum —")
w("`CREATE TYPE pettycash_test.system_role AS ENUM ('normal','admin','superadmin')` —")
w("but **the column is commented out** in the `user` table, at both the live")
w("definition and the dead `/* */` block above it. No column anywhere uses that type.")
w("")
w("It was commented out in the original `01_schema 2.sql`, with no reason given, and")
w("the rebase inherited it. The application depends on it:")
w("")
w("| | |")
w("|---|---|")
w("| declared | [blueprints/auth/models/user.py:41](blueprints/auth/models/user.py#L41) |")
w("| gates superuser at login | [blueprints/auth/routes/login.py:31](blueprints/auth/routes/login.py#L31), [blueprints/auth/routes/email_auth.py:48](blueprints/auth/routes/email_auth.py#L48) |")
w("| written | [blueprints/invitation/services/invite.py:82](blueprints/invitation/services/invite.py#L82) |")
w("| read | [blueprints/user_management/routes/admin_dashboard.py:38](blueprints/user_management/routes/admin_dashboard.py#L38), [blueprints/legal/routes/accept.py:134](blueprints/legal/routes/accept.py#L134) |")
w("| mirrored in billing-backend | [shared_models/models.py:13](shared_models/models.py#L13) |")
w("")
w("There is nowhere else to put a global superuser flag — `user_entity.role` is")
w("per-entity and `role` is a different concept. Uncommenting the column is the fix;")
w("the enum is already there and already correct. Until then the superuser gate has")
w("no backing store.")
w("")
w("---")
w("")
w("## 1. Renamed tables — %d" % len(tables))
w("")
w("`__tablename__` / `db_table` no longer resolves. Nothing on these models works.")
w("")
w("| repo | old | new | declared at |")
w("|---|---|---|---|")
for r in sorted(tables, key=lambda r: (r["repo"], r["table"])):
    w("| %s | `%s` | `%s` | %s |" % (r["repo"], r["table"],
                                     RENAME.get(r["table"], "**?**"), link(r)))
w("")
w("The class names follow the table where it reads oddly otherwise —")
w("`ShopExpense` becomes report_expense, `ReportSaleDetail` becomes report_sale.")
w("Both are more than renames: check the column lists in section 2 before assuming")
w("a one-line change.")
w("")
w("---")
w("")
w("## 2. Model columns the schema does not have — %d" % len(missing))
w("")
w("**These break every SELECT on the model**, not just writes: an ORM selects all")
w("mapped columns, so one stale attribute takes the whole table down. Fix these first.")
w("")
by = collections.OrderedDict()
for r in sorted(missing, key=lambda r: (r["repo"], r["file"], r["line"])):
    by.setdefault((r["repo"], r["file"], r["table"]), []).append(r)
for (repo, f, t), rs in by.items():
    w("#### `%s` — %s (%s)" % (t, f, repo))
    w("")
    for r in rs:
        w("- `%s` — line %d" % (r["what"], r["line"]))
    w("")
w("---")
w("")
w("## 3. Declared types that no longer match — %d" % len(types))
w("")
cnt = collections.Counter(r["what"].rsplit("schema is ", 1)[-1] for r in types)
w("| schema type | count | what the models declare |")
w("|---|---|---|")
w("| `uuid` | %d | `db.String(36)` / `models.CharField(max_length=36)` |" % cnt["uuid"])
w("| `numeric` | %d | `db.Float` — money, so this one is a correctness fix, not cosmetic |" % cnt["numeric"])
w("| enums | %d | `db.String` / `models.CharField(choices=...)` |"
  % sum(v for k, v in cnt.items() if k not in
        ("uuid", "numeric", "timestamp with time zone", "character", "smallint", "jsonb", "date")))
w("| `timestamp with time zone` | %d | `db.DateTime` with no `timezone=True` |" % cnt["timestamp with time zone"])
w("| other | %d | `character`, `smallint`, `jsonb`, `date` |"
  % (cnt["character"] + cnt["smallint"] + cnt["jsonb"] + cnt["date"]))
w("")
w("None of these stops the app the way section 2 does — Postgres casts a great deal")
w("on the way in. They matter for a different reason:")
w("")
w("- **`uuid` vs `String(36)`** — comparisons still work, but an index on a uuid")
w("  column is not used the same way when the parameter arrives as text, and a")
w("  malformed value fails at the database rather than in validation.")
w("- **`numeric` vs `Float`** — this one is a real bug. Binary floating point cannot")
w("  represent money exactly; the schema moved to `numeric` deliberately and a model")
w("  still declaring `Float` reintroduces the rounding the change was meant to remove.")
w("- **enum vs `String`** — the database now rejects a value outside the enum. That is")
w("  the point, but it turns a silent bad write into a 500, so it wants testing.")
w("- **`DateTime` without `timezone=True`** — the column is `timestamptz`; a naive")
w("  datetime is normalised to the *session* timezone, not to UTC.")
w("")
w("Full list, grouped by file:")
w("")
byf = collections.OrderedDict()
for r in sorted(types, key=lambda r: (r["repo"], r["file"], r["line"])):
    byf.setdefault((r["repo"], r["file"]), []).append(r)
for (repo, f), rs in byf.items():
    w("<details><summary><code>%s</code> (%s) — %d</summary>" % (f, repo, len(rs)))
    w("")
    for r in rs:
        w("- line %d: %s" % (r["line"], r["what"]))
    w("")
    w("</details>")
    w("")
w("---")
w("")
w("## 4. Behavioural change: `entity_function_map.created_by`")
w("")
w("Not a type mismatch — the audit passes it, because the model and the schema now")
w("disagree about *meaning* rather than about type. Recorded as item 10 of the")
w("decision register in `01_schema_rebased.sql`.")
w("")
w("The column is a foreign key to `user`. The code writes an actor **label**:")
w("")
w("| | |")
w("|---|---|")
w("| the only write site | [blueprints/entity/services/modules.py:534](blueprints/entity/services/modules.py#L534), inside `_write_pairs` at [:497](blueprints/entity/services/modules.py#L497) |")
w("| the labels | [blueprints/entity/services/modules.py:60-62](blueprints/entity/services/modules.py#L60-L62) — `onboarding`, `cli`, `entity_create` |")
w("| callers | [blueprints/entity/routes/create.py:1169](blueprints/entity/routes/create.py#L1169), [blueprints/entity/services/modules.py:393](blueprints/entity/services/modules.py#L393), [blueprints/entity/routes/settings.py:1921](blueprints/entity/routes/settings.py#L1921) (`\"subscription\"`) |")
w("| model | [blueprints/entity/models/entity_function.py:34](blueprints/entity/models/entity_function.py#L34) — `String(36)`, no ForeignKey |")
w("| tests | `tests/test_module_access_gate.py:86`, `tests/test_onboarding_module_state.py:77` |")
w("")
w("`_write_pairs` needs a user id parameter. Two of the four callers — `cli` and")
w("`subscription` — are jobs with no user, so their rows land `NULL` and the four")
w("paths stop being distinguishable. A nullable `actor VARCHAR(20)` beside the column")
w("keeps that provenance if it is wanted; not assumed here.")
w("")
w("---")
w("")
w("## Order to do this in")
w("")
w("0. **Settle D1–D5** (section 0). Two of them change what the data says, so anything")
w("   built against the current values may be built against the wrong ones.")
w("1. **Uncomment `user.system_role`** — D6, its own section above. A schema edit, and")
w("   everything else is easier once the schema is settled.")
w("2. **Section 2, the missing columns.** Nothing can be tested until an ORM query")
w("   against these tables runs at all.")
w("3. **Section 1, the renames.** Mechanical once the columns are right.")
w("4. **Section 3's `numeric` rows.** The money bug is the only type finding that is")
w("   wrong rather than merely untidy.")
w("5. **Section 4**, whenever — the column accepts `NULL`, so nothing breaks meanwhile.")
w("6. The rest of section 3 as tidy-up.")
w("")

io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(d) + "\n")
print("wrote", OUT, "-", len(rows), "findings")
